# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce6ae5280fea6b2402c657c67accbb74aabcb31df0ed7f468bfe37bee26b24294fc00182979cb1565e765f879963b158b109eacda71427365b0cdaca06874ecc

test:
  secret_key_base: 797b7df911972bf7d7ef3de832c80becafe127a6332f1c5d627e69518f3d8c9456751f87481124bc8562e913aa86f0464cebceb6fa0f5e83838f0d0cd743f1b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
